# Generated by Django 4.0.1 on 2022-01-29 18:59

import depositapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depositapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit',
            field=models.JSONField(default=depositapi.models.Deposit.deposit_default),
        ),
    ]
